_target_: optispeech.model.generator.PitchPredictor
_partial_: true
n_layers: 5
intermediate_dim: 384
kernel_size: 5
conv_layer_class:
  _target_: optispeech.model.generator.layers.ConvSeparable
  _partial_: true
activation: relu
dropout: 0.1
max_source_positions: 2000
