defaults:
  - _self_
  - generator: default.yaml
  - optimizer: adamw.yaml
  - scheduler: exponential_decay.yaml

_target_: optispeech.model.OptiSpeech
dim: 256
n_feats: ${data.n_feats}
n_fft: ${data.n_fft}
hop_length: ${data.hop_length}
sample_rate: ${data.sample_rate}
f_min: ${data.f_min}
f_max: ${data.f_max}
language: ${data.language}
tokenizer: ${data.tokenizer}
add_blank: ${data.add_blank}
data_statistics: ${data.data_statistics}
