defaults:
  - _self_
  - generator: default
  - discriminator: default
  - optimizer: adamw
  - scheduler: exponential_decay

_target_: optispeech.model.OptiSpeech
dim: 256
train_args:
  cache_generator_outputs: true
  decay_mel_coeff: false
  gradient_clip_val: 1.0
  gradient_accumulate_batches: null
  pretraining_steps: 1000
data_args:
  text_processor: ${data.text_processor}
  feature_extractor: ${data.feature_extractor}
  batch_size: ${data.batch_size}
  data_statistics: ${data.data_statistics}
