_target_: optispeech.model.generator.DurationPredictor
_partial_: true
n_layers: 2
intermediate_dim: 384
kernel_size: 3
conv_layer_class:
  _target_: optispeech.model.generator.layers.ConvSeparable
  _partial_: true
activation: relu
dropout: 0.1
